[workspace]
# A separate workspace

[package]
name = "sea-orm-issue-2383"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "issue-2383"
path = "src/main.rs"

[dependencies]
serde = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }

[dependencies.sea-orm]
path = "../../"
default-features = false
features = [
    "macros",
    "runtime-tokio-native-tls",
    "sqlx-postgres",
    "postgres-array",
]
